# This file configures the `simp_rpm_helper` script.
#
# simp_rpm_helper can ensure that RPM-delivered SIMP assets (which are
# installed into /usr/share/simp) are moved to the appropriate locations
---
# Target directory
#
# May be set to a fully-qualified path or 'auto'
# If set to 'auto', the directory will be determined from puppet itself
# target_directory : 'auto'

# Copy the RPM data to the target directory
# copy_rpm_data : false
